---
GITHUB: git
GITHUB_ROOT: git://github.com
GITHUB_PUSH_ROOT: "git@github.com:"
SPACEGIT: http
SPACEGIT_ROOT: 'https://git.hb.dfki.de'
SPACEGIT_PUSH_ROOT: 'https://git.hb.dfki.de'
DFKIGIT: http
DFKIGIT_ROOT: 'https://git.hb.dfki.de'
DFKIGIT_PUSH_ROOT: 'https://git.hb.dfki.de'
ROCK_SELECTED_FLAVOR: master
ROCK_BRANCH: master
cxx11: true
typelib_cxx_loader: castxml
ldgold: true
NDLCOM_ROBOTCONFIG: CommonConfig
DROCK_USE_BLENDER: false
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
ccache: true
ccacheDir: default
ccacheSize: 10G
iceCC: true
iceCC_parallel: '15'
osdeps_mode: all
apt_dpkg_update: true
SPACEAPP: http,http
SPACEAPP_ROOT: 'https://gitlab.com'
SPACEAPP_PUSH_ROOT: 'https://gitlab.com'
SPACEAPP_PRIVATE_ROOT: 'https://gitlab.com'
CDFF_EXTERNAL_SOURCE_INSTALL: all
USE_PYTHON: true
python_executable: "/usr/bin/python3.6"
python_version: '3.6'
