---
prefer_indep_over_os_packages: false
osdeps_mode: all
apt_dpkg_update: false
GITHUB: http,ssh
GITHUB_ROOT: https://github.com
GITHUB_PUSH_ROOT: 'git@github.com:'
GITHUB_PRIVATE_ROOT: 'git@github.com:'
DFKIGIT: http,ssh
DFKIGIT_ROOT: https://git.hb.dfki.de
DFKIGIT_PUSH_ROOT: 'git@git.hb.dfki.de:'
DFKIGIT_PRIVATE_ROOT: 'git@git.hb.dfki.de:'
GITLAB: http,ssh
GITLAB_ROOT: https://gitlab.com
GITLAB_PUSH_ROOT: 'git@gitlab.com:'
GITLAB_PRIVATE_ROOT: 'git@gitlab.com:'
ROCK_SELECTED_FLAVOR: master
ROCK_FLAVOR: master
ROCK_BRANCH: master
typelib_cxx_loader: castxml
USE_PYTHON: true
python_executable: "/usr/bin/python3"
syskit_use_bundles: true
NDLCOM_ROBOTCONFIG: Crex
USE_OCL: false
rtt_target: gnulinux
rtt_corba_implementation: omniorb
ldgold: false
ccache: false
